import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.Collections;

import javax.swing.JOptionPane;

/** Array list told hold the high scores for the game
 * @author Jared Moore
 * @version Nov 17, 2012
 */
public class LeaderBoard implements Serializable {

	/** Used to make sure the objects in the file are the correct version of this class 
	 */
	private static final long serialVersionUID = 7487390213792955281L;
	private ArrayList<Score> scores;
	
	/** Constructor for LeaderBoard 
	 */
	public LeaderBoard() {
		
		ObjectInputStream input;
		try {
			input = new ObjectInputStream(new FileInputStream("res/scores.ser"));
			scores = (ArrayList<Score>) input.readObject();
		} catch (IOException e) { // there is no file, just make a new ArrayList
			scores = new ArrayList<Score>(10);
		} catch (ClassNotFoundException e) {
			System.err.println("Classes do not match.  You are not using a file generated by this program");
			System.exit(1);
		}		
	}
	
	/** Add an element to the list, keeping it in order
	 * @param time The amount of time it took to win
	 * @param rows The amount of rows of tiles
	 * @param columns The amount of columns of tiles
	 * @param mines The amount of mines 
	 * @param name The name of the player who won
	 */
	public void add(int time, int rows, int columns, int mines, String name) {
		
		Score score = new Score(rows, columns, mines, time, name);
		
		if (scores.size() == 0)
			scores.add(score);
		else {
			int index = 0;
			for (int i = 0; i < scores.size(); i++) {
				index = i;
				if (scores.get(i).compareTo(score) > 0) {
					if (i == scores.size() - 1) // this is the last iteration, so set index to be the last element
						index++;
					continue; // move to next iteration
				}
				else 
					break; // insert score at index i
			}
			if (index < 10)
				scores.add(index, score);
		}
		
		// write to the file
		try {
			ObjectOutputStream output = new ObjectOutputStream(new FileOutputStream("res/scores.ser"));
			output.writeObject(scores);
			output.close();
		} catch (IOException e) {
			System.err.println("Error opening/writing to file, may not have write permission in current directory");
			e.printStackTrace(); // so you can see what went wrong
			System.exit(1);
		}
	}
	
	/** Displays the top ten high scores in a JOptionPane, in order from best to worst
	 */
	public void display() {
		
		if (scores.size() > 0) {
			String output = "";
			for (int i = 0; i < scores.size(); i++) 
				output += (i + 1) + ") " + scores.get(i).toString() + "\n";
			JOptionPane.showMessageDialog(null, output);
		}
		else 
			JOptionPane.showMessageDialog(null, "There are no scores to display");
	}
}
